"""empty message

Revision ID: 19be397924f5
Revises: 
Create Date: 2022-09-25 14:42:08.105033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19be397924f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('last_use', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_action', sa.Enum('VOICE_MESSAGE', 'VIDEO_NOTE', 'AUDIO_FILE', 'RANDOM_ACTION', name='user_action'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_info')
    op.drop_table('user')
    # ### end Alembic commands ###
