"""empty message

Revision ID: 423dd1d764ae
Revises: 19be397924f5
Create Date: 2022-09-25 15:10:21.525713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423dd1d764ae'
down_revision = '19be397924f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
